# ClangFormat
# Author: Eliot Hall
# This program formats all cpp files in the repository
name: ClangFormat

on:
  pull_request:
    branches: ["master"] 
  push:
    branches: ["master"]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Format .cpp and .hpp files
        run:
          clang-format ${{github.workspace}}/src/*.cpp ${{github.workspace}}/include/botui/*.h -style=file:${{github.workspace}}/.clang-format -i
      - name: Setup git config
        run: |
          git config user.name "Clang Formatter Bot"
          git config user.email ""
      - name: Push to GitHub
        run:  |
          echo ${{github.head_ref}}
          echo ${{github.base_ref}}
          echo ${{github.action_ref}}
          echo ${{github.ref}}
          echo ${{github.ref_name}}
          git commit -a -m "AutoFormat with clang-format"
          git push origin HEAD:${{github.head_ref}}
          